import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next on every build and trips the
  // triple-slash-reference rule; it is gitignored and not ours to edit.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
];

export default config;
